name: Update Live Screenshot

on:
  push:
    branches:
      - main
    paths:
      - index.html
      - static/**
  deployment_status:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  screenshot:
    # Run only if:
    # 1. It's NOT a deployment_status event, OR
    # 2. It's a deployment_status AND the build succeeded
    if: github.event_name != 'deployment_status' || github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Take screenshot
        run: |
          node <<'EOF'
          const puppeteer = require('puppeteer');
          (async () => {
            const browser = await puppeteer.launch({ args: ['--no-sandbox'] });
            const page = await browser.newPage();
            await page.goto('https://wed-2023.github.io/assignment2-206515744_209406255_assignment2', { waitUntil: 'networkidle2' });
            await page.setViewport({ width: 1280, height: 720 });
            await page.screenshot({ path: 'preview.png' });
            await browser.close();
          })();
          EOF

      - name: Generate timestamp for cache busting
        run: echo "VERSION=$(date +%s)" >> $GITHUB_ENV

      - name: Update README.md with new version
        run: |
          sed -i "s/preview.png?v=[0-9]*/preview.png?v=${VERSION}/" README.md

      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add preview.png README.md
          git diff --cached --quiet || git commit -m "Update screenshot with cache busting"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git push origin HEAD
